name: Flutter Web Deploy

on:
  push:
    branches: [ "main" ]        # mỗi lần merge/push vào main là chạy

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'   # đúng version bạn đang dùng
          channel: 'stable'

      - name: Clean previous build
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        # repo tên portal_log => base-href nên là /portal_log/
        run: flutter build web --release --base-href="/portal_log/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web     # chỗ flutter build web xuất ra
          publish_branch: gh-pages     # đẩy kết quả lên branch gh-pages
          force_orphan: true           # cho nhánh gh-pages chỉ chứa file build
